### ISSUE TITLE
use of notifiers for page footers

### ISSUE THREAD

**Issue by torvista** [lat9/super_globals_plus#16]
Is this not possible now, to avoid touching the files?

**Comment by lat9** [comment]
I'm _very_ hesitant to use template-based notifiers, since most of the templates that are "out there" don't include that notifier.

**Comment by torvista** [comment]
If the instructions still mention how to add it manually, is that not a problem for those behind the curve to deal with?

**Comment by lat9** [comment]
Point taken; it's an edit one way or the other.

**Comment by lat9** [comment]
Noting that the admin `footer.php` notification has been "baked in" since zc156b and that the notification for the template's `common/tpl_footer.php` has been "baked in" since zc155.

No notification currently exists to enable the _Super Globals_ display on the admin home-page (i.e. `index.php`), so that core-file update remains if that function is desired.
